name: Trigger validation

on:
  workflow_call:
    inputs:
      boinor-branch:
        description: 'boinor branch to validate'
        default: 'main'
        required: false
        type: string
      validation-branch:
        description: 'validation branch to validate'
        default: 'main'
        required: false
        type: string

jobs:
  validation-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13, 3.14, 3.15, 3.14t, 3.15t, pypy3.11]

    steps:
      - uses: actions/checkout@v6
        with:
           repository: 'boinor/boinor'
           ref: ${{ inputs.boinor-branch }}
           path: boinor
        
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          
      - name: install the package
        run: python3 -m pip install .
        working-directory: boinor

      - uses: actions/checkout@v6
        with:
           repository: 'boinor/validation'
           ref: ${{ inputs.validation-branch }}
           path: validation

# Execute tests to check if they are still valid for new features
  orekit-validation-tests:
    name: Orekit validation tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13, 3.14]
    defaults:
      run:
        shell: bash -l {0}

    # Steps to be executed during tests checking job
    steps:
      - uses: actions/checkout@v6
        with:
           repository: 'eitan-j/boinor'
           ref: ${{ inputs.boinor-branch }}
           path: boinor
        
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install the package
        run: python3 -m pip install .
        working-directory: boinor

      - uses: actions/checkout@v6
        with:
           repository: 'eitan-j/validation'
           ref: ${{ inputs.validation-branch }}
           path: validation-orekit

      # Install miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: validation-orekit/orekit/environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: boinor-validation
      - run: |
          conda info
          conda list
          # pytest orekit/tests/
