name: Trigger validation

on:
  workflow_call:
    inputs:
      boinor-branch:
        description: 'boinor branch to validate'
        default: 'main'
        required: false
        type: string
      validation-branch:
        description: 'validation branch to validate'
        default: 'main'
        required: false
        type: string

jobs:
  validation-tests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
        with:
           repository: 'boinor/boinor'
           ref: ${{ inputs.boinor-branch }}
           path: boinor
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install the package
        run: python3 -m pip install .
        working-directory: boinor

      - uses: actions/checkout@v4
        with:
           repository: 'boinor/validation'
           ref: ${{ inputs.validation-branch }}
           path: validation

      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "validation/orekit/"
          use-black: true
          use-flake8: true
          use-isort: false
          use-pylint: false
          use-pycodestyle: false
          use-mypy: false
          # Tool's configuration is the same as boinor
          extra-black-options: "--check --diff"
          extra-isort-options: "--check-only --diff"
          extra-flake8-options: "--ignore=E203,E266,E501,W503 --max-line-length=80 --max-complexity=18 --select=B,C,E,F,W,T4,B9"

# Execute tests to check if they are still valid for new features
  orekit-validation-tests:
    name: Orekit validation tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    defaults:
      run:
        shell: bash -l {0}

    # Steps to be executed during tests checking job
    steps:
      - uses: actions/checkout@v4
        with:
           repository: 'boinor/boinor'
           ref: ${{ inputs.boinor-branch }}
           path: boinor
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install the package
        run: python3 -m pip install .
        working-directory: boinor

      - uses: actions/checkout@v4
        with:
           repository: 'boinor/validation'
           ref: ${{ inputs.validation-branch }}
           path: validation-orekit

      # Install miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: validation-orekit/orekit/environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: boinor-validation
      - run: |
          conda info
          conda list
          # pytest orekit/tests/
